In [1]:
# Tensors tutorial

# preliminary
import torch
import numpy as np

In [2]:
# Initializing tensors
# this is manually, and datatype is automatically inferred
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
# Alternatively, we can also use numpy arrays (more common)
np_array = np.array(data)
# convert from tensor back to numpy array
x_np = torch.from_numpy(np_array)

In [4]:
# can also concatenate from another tensor
# this retains the properties of the x_data
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

# overrides the datatype of x_data, may be useful in some situations
# torch.rand_like generates these from a uniform 0,1 dist
# rand_like generatesa andom tensor te same size as another tensor, i.e. convenience function
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensors: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensors: 
 tensor([[0.4405, 0.5021],
        [0.1997, 0.9122]]) 



In [5]:
# Attributes of a tensor
# rand is the BASE function that requires you to specify the dimensions manually
tensor = torch.rand(3, 4)
# three main attributes we care about
tensor.shape
tensor.dtype
tensor.device

device(type='cpu')

In [6]:
# Operations on Tensors
# By defualt, all tensor operators are on CPU
# and you need to move tensors to GPU for speedup manually

# These are called "accerlerators"
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [7]:
# Tensor API is very similar to NumPy API
# recall that Python has 0 based indexing
tensor = torch.from_numpy(np.array(range(0, 16)).reshape(4, 4))
# First row
tensor[0, :]
# First Columns
tensor[:, 0]
# Last column (unique Python based indexing)
# tensor[:, -(1)]

tensor([ 0,  4,  8, 12])

In [8]:
# Joining Tensors
# rbind
torch.cat([tensor, tensor], dim = 0)
# cbind
torch.cat([tensor, tensor], dim = 1)

# stack is somewhat different, essentially stacks the arrays to yield a higher dimensional object
# e.g. 2d -> 3d
# the dim arument in this case corresponds to where you want the dimension to increase/stacked
three_d = torch.stack([tensor, tensor], dim = 2)
three_d.shape
# torch.stack([three_d, three_d], dim = 0).shape

torch.Size([4, 4, 2])

In [9]:
# Arithmetic Operators
# @ is used for  MATRIX mutiplication
# .T is used  Transpose a tensor
y1 = tensor @ tensor.T
print(y1)

# alternatively, using the clunky OOP approach
y2 = tensor.matmul(tensor.T)
print(y2)

# Elementwise multiplication
# uses asterisk * instead (similar to R)
z1 = tensor * tensor
z2 = tensor.mul(tensor)
# rand_like only works with floats, so dtype conversion is necessary
z3 = torch.rand_like(tensor, dtype = torch.float)

torch.mul(tensor, tensor, out = z3)

tensor([[ 14,  38,  62,  86],
        [ 38, 126, 214, 302],
        [ 62, 214, 366, 518],
        [ 86, 302, 518, 734]])
tensor([[ 14,  38,  62,  86],
        [ 38, 126, 214, 302],
        [ 62, 214, 366, 518],
        [ 86, 302, 518, 734]])


tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.]])

In [10]:
# Converting this back to a numebr can be done via item()
# sum of a tensor
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

120 <class 'int'>


In [11]:
# In place operators
# These directly manipulate the object and store them in place
# These are against the principles of Functional Programming
# Denoted with a _ suffix
# e.g.
# x.copy_(y), x.t_() will all change x
print(tensor)
tensor.add_(5)
print(tensor)
tensor.subtract_(5)
print(tensor)

# These are mainly useful for saving memory
# However, they erase history, which can fuck up derivatives later on
# Try to avoid

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [13]:
# Bridging this with NumPy
# print f is for printing formatted string literals
t = torch.ones(5)
print(f"t: {t}")
# convert to numpy
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
